// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgrxdypaqncmrmwdrohg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJncnhkeXBhcW5jbXJtd2Ryb2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTM4NTUsImV4cCI6MjA2MDI2OTg1NX0.RE0x34Q6cy4fTVccgznj8D7jJ8-xZ-IHoqzuJS0ExHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);